spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect